"""First migration

Revision ID: b3c181443465
Revises: 0ac1ef8eadad
Create Date: 2022-02-11 07:15:01.123254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c181443465'
down_revision = '0ac1ef8eadad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('meter-types_customer_id_fkey', 'meter-types', type_='foreignkey')
    op.create_foreign_key(None, 'meter-types', 'customers', ['customer_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meter-types', type_='foreignkey')
    op.create_foreign_key('meter-types_customer_id_fkey', 'meter-types', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###
